Repository Ustroytelling/us-server, pull requests merged in 2024-01, with the labels that each got.

#11 보관함(Bookshelf)기능 구현 완료
  src/main/java/us/usserver/author/Author.java
  src/main/java/us/usserver/author/dto/AuthorInfo.java
  src/main/java/us/usserver/authority/AuthorService.java
  src/main/java/us/usserver/authority/AuthorityController.java
  src/main/java/us/usserver/authority/AuthorityService.java
  src/main/java/us/usserver/authority/service/AuthorServiceV0.java
  src/main/java/us/usserver/authority/service/AuthorityServiceV0.java
  src/main/java/us/usserver/bookshelf/Bookshelf.java
  src/main/java/us/usserver/bookshelf/BookshelfController.java
  src/main/java/us/usserver/bookshelf/BookshelfService.java
  src/main/java/us/usserver/bookshelf/dto/NovelPreview.java
  src/main/java/us/usserver/bookshelf/service/BookshelfServiceV0.java
  src/main/java/us/usserver/chapter/service/ChapterServiceV0.java
  src/main/java/us/usserver/like/novel/NovelLike.java
  src/main/java/us/usserver/like/novel/NovelLikeRepository.java
  src/main/java/us/usserver/novel/Novel.java
  src/main/java/us/usserver/novel/NovelController.java
  src/main/java/us/usserver/novel/service/NovelServiceV0.java
  src/main/java/us/usserver/stake/StakeController.java
  src/test/java/us/usserver/bookshelf/service/BookshelfServiceV0Test.java
  src/test/java/us/usserver/stake/service/StakeServiceV0Test.java
Labels: enhancement

#13 로그인, 회원가입 기능 구현 완료
  build.gradle
  src/main/java/us/usserver/author/AuthorRepository.java
  src/main/java/us/usserver/global/EntityService.java
  src/main/java/us/usserver/global/ExceptionMessage.java
  src/main/java/us/usserver/global/GlobalControllerAdvice.java
  src/main/java/us/usserver/global/RedisUtils.java
  src/main/java/us/usserver/global/SecurityConfig.java
  src/main/java/us/usserver/global/exception/MemberNotFoundException.java
  src/main/java/us/usserver/global/exception/TokenInvalidException.java
  src/main/java/us/usserver/global/jwt/JwtAuthenticationFilter.java
  src/main/java/us/usserver/global/jwt/TokenProvider.java
  src/main/java/us/usserver/global/oauth/CustomOAuth2UserService.java
  src/main/java/us/usserver/global/oauth/CustomOauth2User.java
  src/main/java/us/usserver/global/oauth/OauthAttributes.java
  src/main/java/us/usserver/global/oauth/OauthController.java
  src/main/java/us/usserver/global/oauth/handler/Oauth2LoginFailureHandler.java
  src/main/java/us/usserver/global/oauth/handler/Oauth2LoginSuccessHandler.java
  src/main/java/us/usserver/global/oauth/oauthEnum/SocialType.java
  src/main/java/us/usserver/global/oauth/userinfo/GoogleOauth2UserInfo.java
  src/main/java/us/usserver/global/oauth/userinfo/KakaoOauth2UserInfo.java
  src/main/java/us/usserver/global/oauth/userinfo/NaverOauth2UserInfo.java
  src/main/java/us/usserver/global/oauth/userinfo/Oauth2UserInfo.java
  src/main/java/us/usserver/member/Member.java
  src/main/java/us/usserver/member/MemberController.java
  src/main/java/us/usserver/member/MemberRepository.java
  src/main/java/us/usserver/member/MemberService.java
  src/main/java/us/usserver/member/dto/JoinMemberReq.java
  src/main/java/us/usserver/member/dto/LoginMemberResponse.java
  src/main/java/us/usserver/member/memberEnum/Gender.java
  src/main/java/us/usserver/member/memberEnum/Role.java
  src/main/java/us/usserver/member/service/MemberServiceV0.java
  src/main/resources/application.yml
Labels: enhancement

#14 내 정보 기능 구현 완료
  src/main/java/us/usserver/author/Author.java
  src/main/java/us/usserver/author/AuthorController.java
  src/main/java/us/usserver/author/AuthorService.java
  src/main/java/us/usserver/author/dto/UpdateAuthorReq.java
  src/main/java/us/usserver/author/service/AuthorServiceV0.java
  src/main/java/us/usserver/global/oauth/OauthAttributes.java
  src/main/java/us/usserver/global/oauth/OauthController.java
  src/main/java/us/usserver/member/MemberController.java
  src/main/java/us/usserver/member/MemberService.java
  src/main/java/us/usserver/member/service/MemberServiceV0.java
  src/main/java/us/usserver/novel/NovelController.java
  src/main/java/us/usserver/novel/NovelService.java
  src/main/java/us/usserver/novel/dto/SearchNovelReq.java
  src/main/java/us/usserver/novel/service/NovelServiceV0.java
Labels: enhancement

#16 테스트 오류 수정
  .gitignore
  build.gradle
  src/main/java/us/usserver/author/dto/AuthorInfo.java
  src/main/java/us/usserver/global/ApiCsResponse.java
  src/main/java/us/usserver/member/Member.java
  src/main/java/us/usserver/novel/Novel.java
  src/main/java/us/usserver/novel/NovelController.java
  src/main/java/us/usserver/novel/service/NovelServiceV0.java
  src/main/resources/application.yml
  src/test/java/us/usserver/bookshelf/service/BookshelfServiceV0Test.java
  src/test/java/us/usserver/chapter/service/ChapterServiceV0Test.java
  src/test/java/us/usserver/comment/service/CommentServiceV0Test.java
  src/test/java/us/usserver/like/novel/service/NovelLikeServiceV0Test.java
  src/test/java/us/usserver/like/paragraph/service/ParagraphLikeServiceV0Test.java
  src/test/java/us/usserver/member/MemberMother.java
  src/test/java/us/usserver/note/service/NoteServiceV0Test.java
  src/test/java/us/usserver/novel/service/NovelServiceV0Test.java
  src/test/java/us/usserver/paragraph/service/ParagraphServiceV0Test.java
  src/test/java/us/usserver/score/service/ScoreServiceV0Test.java
  src/test/java/us/usserver/stake/service/StakeServiceV0Test.java
  src/test/java/us/usserver/vote/service/VoteServiceV0Test.java
  system.properties
Labels: fix

#17 [docs] application-env.yml 값들 서버 내 환경 변수로 이전
  src/main/java/us/usserver/global/config/RedisConfig.java
  src/main/java/us/usserver/global/jwt/TokenProvider.java
Labels: documentation

#18 [docs] env 수정
  src/main/resources/application.yml
Labels: documentation

#20 [cicd] production yml파일 재작성
  .github/workflows/ci.cd.prod.yml
Labels: documentation

#30 [feat] 서브 모듈 활용한 configuration
  .github/workflows/ci.cd.prod.yml
  build.gradle
  src/main/resources/application.yml
Labels: enhancement

#31 [cicd] Github 서브 모듈 사용 방식으로 재정의
  build.gradle
  src/main/resources/application.yml
Labels: documentation
